In [1]:
import math

In [2]:
math.sqrt(25)

5.0

In [3]:
math.pi

3.141592653589793

In [5]:
import math as mt

In [6]:
mt.sqrt(144)

12.0

In [7]:
import numpy as np

In [10]:
from scipy import stats

In [11]:
from numpy import random

In [12]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [13]:
print(dataOne)

[[0.19407799 0.99865757 0.65441695 0.36187057 0.09394964]
 [0.41793752 0.48975625 0.29616132 0.28427651 0.49253649]
 [0.96495802 0.31783804 0.74397136 0.62878121 0.56270925]
 [0.82323743 0.97768    0.6666145  0.17585677 0.17364899]
 [0.95006215 0.72966927 0.38031155 0.21223465 0.82597031]]


In [14]:
np.mean(dataOne)

0.536687372591246

In [15]:
dataOne

array([[0.19407799, 0.99865757, 0.65441695, 0.36187057, 0.09394964],
       [0.41793752, 0.48975625, 0.29616132, 0.28427651, 0.49253649],
       [0.96495802, 0.31783804, 0.74397136, 0.62878121, 0.56270925],
       [0.82323743, 0.97768   , 0.6666145 , 0.17585677, 0.17364899],
       [0.95006215, 0.72966927, 0.38031155, 0.21223465, 0.82597031]])

In [16]:
np.transpose(dataOne)

array([[0.19407799, 0.41793752, 0.96495802, 0.82323743, 0.95006215],
       [0.99865757, 0.48975625, 0.31783804, 0.97768   , 0.72966927],
       [0.65441695, 0.29616132, 0.74397136, 0.6666145 , 0.38031155],
       [0.36187057, 0.28427651, 0.62878121, 0.17585677, 0.21223465],
       [0.09394964, 0.49253649, 0.56270925, 0.17364899, 0.82597031]])

In [19]:
the_world_is_flat = True
if the_world_is_flat:
    print("Be careful not to fall off")

Be careful not to fall off


In [20]:
2+2

4

In [21]:
2*8+9/3 #should be 16+3=19

19.0

In [22]:
5**2 # 5*5=25

25

In [23]:
5^2

7

In [27]:
calc1= 3*5
calc2= 8+2

In [28]:
calc1+_ #15 + 10 =25

37

In [29]:
prefix = "Py"
prefix + 'thon'

'Python'

In [31]:
"ba" + 2*'na'

'banana'

In [32]:
word = 'Python'
word[0]

'P'

In [33]:
word[6]

IndexError: string index out of range

In [34]:
word[2:5]  # characters from position 2 (included) to 5 (excluded)

'tho'

In [35]:
word[:2]   # character from the beginning to position 2 (excluded)
word[4:]   # characters from position 4 (included) to the end

'on'

In [1]:
big_word = 'supercalifragilisticexpialidocious'

In [2]:
len(big_word)

34

In [3]:
squares = [1,4,9,16,25,36,42]

In [4]:
squares

[1, 4, 9, 16, 25, 36, 42]

In [7]:
squares[0], squares[-1], squares[-4]

(1, 42, 16)

In [8]:
squares[:3] #expected 1,4,9

[1, 4, 9]

In [9]:
squares[3:] # expected 16,25,36,42

[16, 25, 36, 42]

In [10]:
#nesting lists
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]

In [11]:
x

[['a', 'b', 'c'], [1, 2, 3]]

In [12]:
x[0]

['a', 'b', 'c']

In [13]:
x[0][2]

'c'

In [14]:
#multiple assignments
a,b,c,d = 2,4,6,8

In [15]:
a,b,c

(2, 4, 6)

In [23]:
#Fibonacci series
a,b = 0,1

In [24]:
while a<150:
    print(a)
    a,b = b,b+a

0
1
1
2
3
5
8
13
21
34
55
89
144


In [27]:
# if statements
x = int(input("Please enter an integer: "))
if x<0:
    x=0
    print('Negative changed to zero')
elif x==0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

Please enter an integer: 5
More


In [28]:
# for statements
words = ['cat','window','defenestrate']
for x in words:
    print(x,len(x))

cat 3
window 6
defenestrate 12


In [30]:
#using range()
for i in range(5):
    print(i)

0
1
2
3
4


In [33]:
 a = ['Mary', 'had', 'a', 'little', 'lamb']
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [38]:
for n in range(2,10):
    for x in range(2,n):
        if n % x == 0:
            print(n,'equals', x, '*', n//x)
            break
    else:
        #Loop fell through without finding a factor.
        print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


In [39]:
#using continue
for num in range(2, 10):
    if num % 2 == 0:
        print("Found an even number", num)
        continue
    print("Found a number", num)

Found an even number 2
Found a number 3
Found an even number 4
Found a number 5
Found an even number 6
Found a number 7
Found an even number 8
Found a number 9


In [50]:
#using more list operators
my_list = ["jan","feb","mar","apr","may","jun","jul"]
print(my_list)

['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul']


In [51]:
my_list.pop(3)

'apr'

In [52]:
print(my_list)

['jan', 'feb', 'mar', 'may', 'jun', 'jul']


In [56]:
my_list.insert(3,"APR")

In [57]:
print(my_list)

['jan', 'feb', 'mar', 'APR', 'may', 'jun', 'jul']


In [58]:
my_list.reverse()

In [59]:
print(my_list)

['jul', 'jun', 'may', 'APR', 'mar', 'feb', 'jan']


In [60]:
cubes = []
for x in range(10):
    cubes.append(x**3)

print(cubes)    

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


In [61]:
del cubes[6]

In [62]:
print(cubes)

[0, 1, 8, 27, 64, 125, 343, 512, 729]


In [64]:
#A set is an unordered collection with no duplicate elements.
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket) # show that duplicates have been removed

{'apple', 'banana', 'pear', 'orange'}


In [65]:
'orange' in basket #check for an existing item in the set.

True

In [66]:
'pineapple' in basket #check for a non-existing item in the set.

False

In [67]:
# Demonstrate set operations on unique letters from two words

a = set('abracadabra')
b = set('alacazam')
a                                  # unique letters in a

a - b                              # letters in a but not in b

a | b                              # letters in a or b or both

a & b                              # letters in both a and b

a ^ b                              # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

In [68]:
#Dictionaries (key-value pairs)
tel = {'jack': 4098, 'sape': 4139}

In [69]:
tel['jack']

4098

In [70]:
dummy_dic = {'jack':70, 'scott':45, 'renee':50, 'beverly':65, 'alex':35}

In [82]:
x = dummy_dic['jack']
y = dummy_dic['renee']
z = dummy_dic['alex']

In [94]:
mt.sqrt(x), mt.gcd(x,y)

(8.366600265340756, 10)

In [98]:
#import a csv file
import os
import pandas as pd

In [96]:
pwd

'C:\\Alejandro\\Jupyter notebooks'

In [100]:
data = pd.read_csv("iris.csv")

In [102]:
data.head(10)

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa
5           6           5.4          3.9           1.7          0.4  setosa
6           7           4.6          3.4           1.4          0.3  setosa
7           8           5.0          3.4           1.5          0.2  setosa
8           9           4.4          2.9           1.4          0.2  setosa
9          10           4.9          3.1           1.5          0.1  setosa